random_seed: 42

stoe: 0.1

transition_matrix:
  E:
    P: 0.8
    I_A: 0.2
  P:
    I_S: 1.0
  I_A:
    R: 1.0
  I_S:
    R: 0.9
    H: 0.1
  H:
    R: 0.95
    D: 0.05
  R:
    S: 1.0

exposed_duration_mean: 3.5
exposed_duration_k: 6

asymptomatic_duration_mean: 10
asymptomatic_duration_k: 6

symptomatic_duration_mean: 10
symptomatic_duration_k: 6

presymptomatic_duration_mean: 2.5
presymptomatic_duration_k: 6

hospital_duration_mean: 6.5
hospital_duration_k: 6

recovered_duration_mean: 200
recovered_duration_k: 6