name: unit-tests
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python for testing
        uses: actions/setup-python@v7
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        env:
            CC: mpicc
            MPICC: mpicc 
        run: pip install -r requirements.txt)
      - name: Unit test with pytest
        run: pytest .
